name: photo
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.2

dependencies:
  google_fonts: ^4.0.3
  flutter_svg: ^1.1.5
  modal_bottom_sheet: ^3.0.0-pre

  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutterfire_cli: ^0.2.7
  firebase_core: ^2.2.0
  google_sign_in: ^5.4.2
  firebase_auth: ^4.1.2
  photo_view: ^0.14.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.14

flutter_native_splash:
  color: "ffffff"
  image: assets/icons/logo.png
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo_square.png"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/Profile1/
    - assets/icons/
    - assets/tab_bar/
    - assets/login_screen/

